### ISSUE TITLE
NOT WORK IN titnaium sdk 6.0.4

### ISSUE THREAD

**Issue by ppatel2zc** [nazrdogan/Ti.IRLDocumentScanner#1]

**Comment by patel-pragnesh** [comment]
great work. hi i like this project, but when run this project give  Error: "Resources" directory not found [ERROR] :  Ensure the "Resources" directory exists and contains an "app.js" file.   Thanks

**Comment by patel-pragnesh** [comment]
NOW WORK. THANKS CLOSE THIS TICKET
